/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A bla.
 */
export type Bla = Base & {
  /**
   * An extra.
   */
  extra?: string;
  [k: string]: unknown;
};

/**
 * The base.
 */
export interface Base {
  /**
   * An original.
   */
  original: boolean;
  [k: string]: unknown;
}
