/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A recipe. For dietary restrictions covered by the recipe, a few common restrictions are enumerated via [[suitableForDiet]]. The [[keywords]] property can also be used to add more detail.
 */
export type Recipe = Butt & {
  /**
   * The time it takes to actually cook the dish, in [ISO 8601 duration format](http://en.wikipedia.org/wiki/ISO_8601).
   */
  cookTime?: string;
  /**
   * The method of cooking, such as Frying, Steaming, ...
   */
  cookingMethod?: string;
  /**
   * A single ingredient used in the recipe, e.g. sugar, flour or garlic.
   */
  ingredients?: string | string[];
  nutrition?: Butt1;
  /**
   * The category of the recipe—for example, appetizer, entree, etc.
   */
  recipeCategory?: string;
  /**
   * The cuisine of the recipe (for example, French or Ethiopian).
   */
  recipeCuisine?: string;
  /**
   * A single ingredient used in the recipe, e.g. sugar, flour or garlic.
   */
  recipeIngredient?: string | string[];
  /**
   * A step in making the recipe, in the form of a single item (document, video, etc.) or an ordered list with HowToStep and/or HowToSection items.
   */
  recipeInstructions?: string | Butt2;
  /**
   * The quantity produced by the recipe (for example, number of people served, number of servings, etc).
   */
  recipeYield?: string | Butt2;
  /**
   * Indicates a dietary restriction or guideline for which this recipe or menu item is suitable, e.g. diabetic, halal etc.
   */
  suitableForDiet?: Butt2 | Butt2[];
  [k: string]: unknown;
};

/**
 * Instructions that explain how to achieve a result by performing a sequence of steps.
 */
export interface Butt {
  foo?: string;
  [k: string]: unknown;
}
/**
 * Nutrition information about the recipe or menu item.
 */
export interface Butt1 {
  foo?: string;
  [k: string]: unknown;
}
export interface Butt2 {
  foo?: string;
  [k: string]: unknown;
}
