/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A recipe. For dietary restrictions covered by the recipe, a few common restrictions are enumerated via [[suitableForDiet]]. The [[keywords]] property can also be used to add more detail.
 */
export type Recipe = HowTo & {
  /**
   * The time it takes to actually cook the dish, in [ISO 8601 duration format](http://en.wikipedia.org/wiki/ISO_8601).
   */
  cookTime?: string;
  /**
   * The method of cooking, such as Frying, Steaming, ...
   */
  cookingMethod?: string;
  /**
   * A single ingredient used in the recipe, e.g. sugar, flour or garlic.
   */
  ingredients?: string | string[];
  /**
   * Nutrition information about the recipe or menu item.
   */
  nutrition?: {
    [k: string]: unknown;
  };
  /**
   * The category of the recipe—for example, appetizer, entree, etc.
   */
  recipeCategory?: string;
  /**
   * The cuisine of the recipe (for example, French or Ethiopian).
   */
  recipeCuisine?: string;
  /**
   * A single ingredient used in the recipe, e.g. sugar, flour or garlic.
   */
  recipeIngredient?: string | string[];
  /**
   * A step in making the recipe, in the form of a single item (document, video, etc.) or an ordered list with HowToStep and/or HowToSection items.
   */
  recipeInstructions?: string;
  /**
   * The quantity produced by the recipe (for example, number of people served, number of servings, etc).
   */
  recipeYield?: string;
  [k: string]: unknown;
};

/**
 * Instructions that explain how to achieve a result by performing a sequence of steps.
 */
export interface HowTo {
  /**
   * The estimated cost of the supply or supplies consumed when performing instructions.
   */
  estimatedCost?: string;
  /**
   * The length of time it takes to perform instructions or a direction (not including time to prepare the supplies), in [ISO 8601 duration format](http://en.wikipedia.org/wiki/ISO_8601).
   */
  performTime?: string;
  /**
   * The length of time it takes to prepare the items to be used in instructions or a direction, in [ISO 8601 duration format](http://en.wikipedia.org/wiki/ISO_8601).
   */
  prepTime?: string;
  /**
   * A single step item (as HowToStep, text, document, video, etc.) or a HowToSection.
   */
  step?: string | string[];
  /**
   * A single step item (as HowToStep, text, document, video, etc.) or a HowToSection (originally misnamed 'steps'; 'step' is preferred).
   */
  steps?: string | string[];
  /**
   * A sub-property of instrument. A supply consumed when performing instructions or a direction.
   */
  supply?: string | string[];
  /**
   * A sub property of instrument. An object used (but not consumed) when performing instructions or a direction.
   */
  tool?: string | string[];
  /**
   * The total time required to perform instructions or a direction (including time to prepare the supplies), in [ISO 8601 duration format](http://en.wikipedia.org/wiki/ISO_8601).
   */
  totalTime?: string;
  /**
   * The quantity that results by performing instructions. For example, a paper airplane, 10 personalized candles.
   */
  yield?: string;
  [k: string]: unknown;
}
